name: Daily - Do npm install and run all unit tests

on:
  schedule:
    # run daily at midnight
    - cron: "0 0 * * *"

jobs:
  build:
    # if: github.repository == 'adobe/aio-cli-lib-app-config'
    uses: adobe/aio-reusable-workflows/.github/workflows/daily.yml@main
