name: on-push-publish-to-npm
on:
  push:
    branches:
      - master # Change this if not your default branch
    paths:
      - 'package.json'
jobs:
  publish:
    # if: github.repository == 'adobe/aio-cli-lib-app-config'
    uses: adobe/aio-resuable-workflows/.github/workflows/on-push-publish-to-npm.yml@main
