name: manual-publish-branch-or-tag
on:
  workflow_dispatch:
    inputs:
      branch-or-tag:
        description: 'The branch or tag to publish from'
        required: false
        default: 'master'
      dry-run:
        description: 'Whether to do a dry-run or not'
        required: false
        default: 'true'
jobs:
  publish:
    if: github.repository == 'adobe/aio-cli-lib-app-config'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-or-tag }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: ${{ github.event.inputs.dry-run }}
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: 'public'
